logging:
  pattern:
    console: "[Practical Java] %clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(---){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
    file: "[Practical Java] %clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(---){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
  file:
    name: log/practical-java.log

spring:
  main:
    banner-mode: OFF
  jackson:
    property-naming-strategy: SNAKE_CASE

server:
  port: 8001

management:
  elastic:
    metrics:
      export:
        step: 30s
        user-name: username
        password: password

springdoc:
  swagger-ui:
    supported-submit-methods:
      - get